name: GitHub CI
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
jobs:
  linux_asan_debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_linux_asan_debug.sh
  osx_11_debug:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_osx_debug.sh